import PriorityBadge from "./PriorityBadge";

interface TriagePanelProps {
  priority: "critical" | "high" | "medium" | "low";
  confidence: number;
  category: string;
  summary: string;
  recommendation: string;
}

export default function TriagePanel({
  priority,
  confidence,
  category,
  summary,
  recommendation,
}: TriagePanelProps) {
  return (
    <div className="rounded-xl border border-(--border-subtle) bg-(--bg-surface) p-6 animate-fade-in">
      {/* Header */}
      <h2 className="font-display text-2xl text-(--text-primary) mb-6">
        Triage Analysis
      </h2>

      {/* Priority Badge */}
      <div className="mb-4">
        <PriorityBadge priority={priority} size="md" />
      </div>

      {/* Confidence */}
      <div className="mb-4">
        <span className="text-sm text-(--text-secondary)">Confidence: </span>
        <span className="text-sm font-bold text-(--text-primary)">{confidence}%</span>
      </div>

      {/* Confidence Bar */}
      <div className="w-full h-1.5 bg-(--bg-surface-raised) rounded-full mb-5 overflow-hidden">
        <div
          className="h-full rounded-full transition-all duration-700"
          style={{
            width: `${confidence}%`,
            background:
              priority === "critical" || priority === "high"
                ? "var(--priority-high)"
                : priority === "medium"
                ? "var(--priority-medium)"
                : "var(--priority-low)",
          }}
        />
      </div>

      {/* Category */}
      <p className="text-sm text-(--text-secondary) mb-6">
        Category: <span className="text-(--text-primary) font-medium">{category}</span>
      </p>

      {/* Auto-generated Summary Card */}
      <div
        className="rounded-lg p-4 border"
        style={{
          backgroundColor: "rgba(161, 135, 50, 0.12)",
          borderColor: "rgba(161, 135, 50, 0.25)",
        }}
      >
        {/* Summary Header */}
        <div className="flex items-center gap-2 mb-3">
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" className="opacity-60">
            <rect x="1" y="1" width="12" height="12" rx="2" stroke="#a18732" strokeWidth="1.5" />
            <path d="M4 7h6M4 5h6M4 9h4" stroke="#a18732" strokeWidth="1" strokeLinecap="round" />
          </svg>
          <span className="text-[10px] font-bold tracking-widest uppercase" style={{ color: "#a18732" }}>
            Autogenerated Summary
          </span>
        </div>

        {/* Summary Text */}
        <p className="text-sm font-medium mb-3" style={{ color: "#e8d9a0" }}>
          {summary}
        </p>

        {/* Recommendation */}
        <div
          className="rounded-md px-3 py-2.5 text-sm"
          style={{
            backgroundColor: "rgba(161, 135, 50, 0.18)",
            color: "#cdb96e",
          }}
        >
          {recommendation}
        </div>
      </div>
    </div>
  );
}
